### ISSUE TITLE
mapping 2Dpoint to 3Dpoint

### ISSUE THREAD

**Issue by TUYaYa1** [arcadelab/deepdrr#103]
Now I have obtained the mapping from 3D to 2D using the following methods：
   ”points_world = [geo.point(p) for p in points]
    points_index = [camera_projection.index_from_world @ p for p in points_world]“
such as 3D point is an array (X,Y,Z) with a shape of (1,3), the 2D point i have obtained is (x,y,1).
This process should be 3D point obtaining a coordinate （x', y', z'）,then (x,y) = (x'/z', y'/z', 1).
Now, I now (x,y) = (x'/z', y'/z', 1), but don't know （x', y', z'）, I want to know how to mapping (x,y) and  (X,Y,Z)

**Comment by benjamindkilleen** [comment]
You cannot map a 2D point to a 3D point, due to the projection operation.

You can however map a 2D point to a 3D line. `p.backproject(index_from_world)` returns the Line3D that corresponds to the pixel.

Alternatively, `index_from_world.inv @ p` gives the vector along this line. You may then want to use the `camera_center_in_world` to march along the ray.

**Comment by TUYaYa1** [comment]
Now, I have 2D points from two different perspectives (i.e. 2D points obtained from different projection angles). Can I mapped 2Dpoint to 3D lines first, and then calculate the intersection of the two 3D lines to obtain the corresponding 3D points of the 2D points?

**Comment by benjamindkilleen** [comment]
This is triangulation, and the problem is the two lines aren't guaranteed to intersect. There are lots of solutions to this in the literature, depending on your exact problem. Szeliski's computer vision is a good reference.
