### ISSUE TITLE
How to implement STL to DCM transformation in deepdrr

### ISSUE THREAD

**Issue by cikitime** [arcadelab/deepdrr#107]
I am particularly interested in understanding the process of integrating tool models, specifically how to convert tool models from STL format into DCM and subsequently how to incorporate them into the final image synthesis.

Despite going through the documentation and the codebase, I find myself uncertain about the steps required to perform this task. Could you please provide some guidance or point me to the relevant documentation or examples in the repository that detail this process?
I am particularly struggling with understanding how to:

Transform the STL file representing the tool into a volume that DeepDRR can use.
Assign material properties to the tool model for accurate simulation.

Thank you for your time and the impressive work on the DeepDRR project.

**Comment by benjamindkilleen** [comment]
The approach you outline is a good one. We have not integrated this pipeline directly into DeepDRR because we don't have an elegant way to do it yet (more on that soon), but you can check out our recently published code from [this paper](https://doi.org/10.1007/978-3-031-43996-4_13). The file you will want to use is [here](https://github.com/benjamindkilleen/pelphix/blob/main/src/pelphix/tools/tool.py).

If you find this helpful, consider citing the paper. Thanks!
