### ISSUE TITLE
Unable to install using pip command

### ISSUE THREAD

**Issue by sainatarajan** [arcadelab/deepdrr#24]
I get the following issue while installing from `pip`:

```
Collecting deepdrr
  ERROR: Could not find a version that satisfies the requirement deepdrr (from versions: none)
ERROR: No matching distribution found for deepdrr
```

I tried a workaround by downloading the repo and running `python setup.py build develop`. It did install, but when I deleted the downloaded repo after installation and tried running the example, it threw me the following error:

```
ModuleNotFoundError: No module named 'deepdrr'
```

How to solve this?

**Comment by mathiasunberath** [comment]
@benjamindkilleen can you take a look, please?

**Comment by benjamindkilleen** [comment]
Hi @sainatarajan the pip install probably didn't work because of your Python version. If you don't have the right version of Python, it will appear like the package is not there. Try with 3.8 or higher.

Second is that, unless I am mistaken, installing from source simply makes a symlink from your Python site-packages to the source directory, so deleting it would be the same as uninstalling.

Thanks for bringing these issues to our attention. They could be clarified in the installation instructions.

**Comment by rm4193** [comment]
I seem to be having this issue when I am using Google Colab. I receive the same error output. Is there something I can do to fix it?
