### ISSUE TITLE
"Fixed" C-arm

### ISSUE THREAD

**Issue by zcc861007** [arcadelab/deepdrr#58]
Hi Arcade Lab,

Previously, I adopted a "fixed" fluoroscope frame to perform 3D-2D co-registration, as shown in the figure below. The global coordinate system was set at the detector. A local coordinate system was defined at the anatomic object, such that the orientation/position of the anatomic object relative to the global coordinate system was determined.

It appears that the MobileCArm class in the DeepDRR adopted an isocenter reference frame. Can I set the frame of the MobileCArm to my frame described above? 

Thank you very much for your suggestion!

![image](https://user-images.githubusercontent.com/33674922/132801315-5f242a1f-c31a-4cd1-a993-0f4fb6bce18a.png)

**Comment by mathiasunberath** [comment]
These coordinate systems are related by one 6 DoF rigid body transformation, so this should be fairly straight forward. Depending on the conventions used in your 2D/3D registration framework, things may become more complicated because you may need to deal with flips resulting from use of OpenGL conventions, etc. We have, however, done this for our own frameworks and know that you can relatively easily do this for our own 2D/3D registration framework xReg, that you can find here: https://github.com/rg2/xreg

**Comment by zcc861007** [comment]
Hi Dr Unberath. I think that I have found the parameters for the setup and volume transformations. Thank you very much for your reminder of flips and directing me to xReg. Also thanks for sharing the amazing tool!
