### ISSUE TITLE
Question on the Euler angles

### ISSUE THREAD

**Issue by antal-huck** [arcadelab/deepdrr#65]
A `MobileCArm` has the method `move_to()` where one can specify two Euler angles alpha and beta.
These angles are then used in `device_from_arm()` and `get_mesh_in_world()`, where alpha is the Euler angle for the x-axis and beta the one for the y-axis.

I would like to compare this to one of your publications, e.g. Fig 4 in https://arxiv.org/pdf/1803.08608.pdf, where CRA/CAU and RAO/LAO angles are varied. If I am not mistaken, the CRA/CAU angle corresponds to an Euler angle of the x-axis and the RAO/LAO angle to the z-axis, with respect to the patient coordinate system, correct?. We notice different hardcoded axes within the methods `device_from_arm()` and `get_mesh_in_world()`.

Of course, axes can be permuted, but I do have some questions:
- Do the hardcoded axes in `device_from_arm()` and `get_mesh_in_world()` intend to correspond to the patient space? Or is this an arbitrary internal representation...
- Where and when should I take care of the orientation of the loaded volume? What is the design/philosophy here? I see for example the `Volume` class method `faceup()` that may setup the internal axes s.t. CRA/CAU corresponds to an Euler angle on the y-axis and RAO/LAO  corresponds to the x-axis.
- Why only two Euler angles? Is this because we mainly use the conventional angles RAO/LAO and CRA/LAU? I would still find it more convenient when one could always feed 3 angles, because (is there another method available that sets up such geometries?):
  1) This way, one would not need to take care of the correct orientation of the volume. We could simply experiment with the 3 angles.
  2) We would not need to perform an additional rotation when applying data augmentation on the DRR for deep learning purposes. Doing this afterwards introduces padding issues.

This concept is new to me, and some things became clear to me while I was writing the question. But maybe you can clarify some things?

**Comment by benjamindkilleen** [comment]
Hello,

These are insightful questions. Let me do my best to answer them in order:
* Since DeepDRR actually supports multiple volumes (which could be tools or overlapping patient CTs), there is a unified world frame in which all the volumes are positioned (by manipulating the `Volume.world_from_anatomical` transform). This is what convenience methods like `Volume.faceup` and `Volume.translate` are doing under the hood. The `device` frame is the C-arm's equivalent, allowing its orientation to be manipulated without affecting the Euler angles.
* See above. TLDR: set `world_from_anatomical`
* These two were sufficient for our purposes. You may wish to sub-class MobileCArm if you would like to add more degrees of freedom. Alternatively, this may already be supported on the `dev` branch.
