### ISSUE TITLE
Hello, how can I use the code for making scatter?

### ISSUE THREAD

**Issue by kimtaeuk-AI** [arcadelab/deepdrr#71]
Hello, thank you for the good code.
I need an image using a scatter.
But, There was a problem with the scatter in #68, is it not solved yet?
It does not seem to work well with test_scatter.py..

Thank you in advance.

**Comment by mathiasunberath** [comment]
Thanks - Scatter is an opportunity for improvement that we are working on, but with moderate urgency. Because the scatter neural network was trained on few samples, the output you will get is not likely to be physically realistic. It will reduce contrast in your image by adding a low frequency modulation, but there's not much more you can do with it. We have been and are working on a fast and physically accurate way of modeling scatter, but it is not currently integrated with the release if I remember correctly - @benjamindkilleen ?

**Comment by benjamindkilleen** [comment]
@kimtaeuk-AI thanks! This feature is currently not released, but if you would like, you can check out the `dev` branch. Setting `scatter_num` to an integer > 0 in the `Projector` object will result in physics-based scatter simulation, with the limitation that this does not support multiple volumes and the caveat that it has not been unit tested. I recommend forking from `dev` if you plan to use this feature, as it is an active branch with frequent changes.

**Comment by kimtaeuk-AI** [comment]
@mathiasunberath @benjamindkilleen  Wow... Thank you so much for your answer. I'll do it now! Thank you~ :)
