### ISSUE TITLE
How can I set window level and window width in code?

### ISSUE THREAD

**Issue by lkccu** [arcadelab/deepdrr#78]
Hi prof @mathiasunberath, I am confused how can I set window level and window width in package deepdrr？

**Comment by mathiasunberath** [comment]
What exactly are you referring to? Usually, the window and level are something that is used for visualization because you want computing to happen on the full bit depth of your images while for visualization you need to compress to 8bit. 
Consequently, DeepDRR does not really handle window leveling and you can chose any visualization software you desire. We often recommend ImageJ as a lightweight option.

**Comment by lkccu** [comment]
> What exactly are you referring to? Usually, the window and level are something that is used for visualization because you want computing to happen on the full bit depth of your images while for visualization you need to compress to 8bit. Consequently, DeepDRR does not really handle window leveling and you can chose any visualization software you desire. We often recommend ImageJ as a lightweight option.

Thank you! I found a similar issue last night and took advantage of ImageJ.
